### PR TITLE
Add support fot stripe v9

### LINKED ISSUE #160: stripe-ruby 9.0 support
Hello!

The Stripe team released [stripe-ruby 9.0](https://github.com/stripe/stripe-ruby/blob/master/CHANGELOG.md#900---2023-08-16) recently.

It does look like there may be some breaking changes in https://github.com/stripe/stripe-ruby/wiki/Migration-guide-for-v9, but would it be possible to support stripe v9 in the [gemspec](https://github.com/integrallis/stripe_event/blob/master/stripe_event.gemspec#L21) file?

Thank you

### PR DESCRIPTION
**Pull request by taise**
Closes #160

Add support for stripe v9

### CODE REVIEW

**Comment by taise** [comment]
Hi @rmm5t,

I'd appreciate it if you review this pull request when you have a moment.
Thanks!

**Comment by mikker** [comment]
I'm running this in production and can confirm that everything works fine.

**Comment by abepark01** [comment]
@taise thank you! It looks like Stripe recently updated their ruby gem to v10.0.0.

**Comment by seanharmer** [comment]
Ping, could we get this merged please? And then also move on to stripe version 10?

**Comment by oboxodo** [comment]
I've just pushed a follow-up PR built on top of this, adding support for stripe 10: #163.

**Comment by AxelTheGerman** [comment]
It also looked to me that there would be no breaking changes that would affect this gem in general (only however folks chose to implement their events)... would be great to get this merged soon

**Comment by mikker** [comment]
fwiw I got tired f waiting and replaced this gem with a homegrown setup. Didn't take much. Here's basically all there is to it if you want to do the same:

https://gist.github.com/mikker/9405c9dc473d07ddfeefec95b38284c0

**Comment by AxelTheGerman** [comment]
> fwiw I got tired f waiting and replaced this gem with a homegrown setup. Didn't take much. Here's basically all there is to it if you want to do the same:
> 
> https://gist.github.com/mikker/9405c9dc473d07ddfeefec95b38284c0

Thanks for sharing, that's a shame because the whole point of gems like this is to reduce the little bit of boilerplate needed there.

Not that I'm expecting lots of development, this is literally feature complete - but without any attention in 4 months this is not passing the bar :disappointed:

**Comment by AxelTheGerman** [comment]
@rmm5t @peterkeen @invisiblefunnel is this something you could still look at or does the community need to move on?

**Pull request closed without merging**
