### PR TITLE
Add support for stripe 9 and 10

### LINKED ISSUE #160: stripe-ruby 9.0 support
Hello!

The Stripe team released [stripe-ruby 9.0](https://github.com/stripe/stripe-ruby/blob/master/CHANGELOG.md#900---2023-08-16) recently.

It does look like there may be some breaking changes in https://github.com/stripe/stripe-ruby/wiki/Migration-guide-for-v9, but would it be possible to support stripe v9 in the [gemspec](https://github.com/integrallis/stripe_event/blob/master/stripe_event.gemspec#L21) file?

Thank you

### PR DESCRIPTION
**Pull request by oboxodo**
This PR is built on top of @taise's yet unmerged stripe9 PR. I'm just adding support for stripe 10 too.

Fixes #160
Closes #162

### CODE REVIEW

**Comment by rickychilcott** [comment]
Very exciting!

**Comment by AxelTheGerman** [comment]
> @rmm5t any chance of you merging this PR and cutting a new release supporting Stripe's v10 gem?

Doesn't look like it. I appreciate all the hard work OSS maintainers do, but ghosting a popular library is quite sad.

**Comment by pedrofs** [comment]
@rmm5t any plan to merge this one?

**Comment by rmm5t** [comment]
> I appreciate all the hard work OSS maintainers do, but ghosting a popular library is quite sad.

@AxelTheGerman Your (typical) selfish behavior is noted.

**Comment by rmm5t** [comment]
[Release v2.8.0 is in the wild](https://rubygems.org/gems/stripe_event)

**Comment by rmm5t** [comment]
Thank you @oboxodo and @taise!

**Pull request merged**
